# Generated by Django 5.2.1 on 2025-10-28 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="join_date",
            new_name="joined_date",
        ),
    ]
